hotel_search_query = [
    "Hotels in London from March 15-18, 2025",
    "Cheap hotels in Paris under $100 per night",
    "Hotels in Tokyo with pool and gym",
    "4-star hotels in Barcelona",
    "Hotels within walking distance of Times Square",
    "Hotels in Las Vegas for 20 people, block of rooms",
    "Unique boutique hotels in Savannah with historic charm",
    "Extended stay hotels in Austin for 2 weeks with kitchenette",
    "Pet-friendly hotels in Seattle that allow large dogs",
    "All-inclusive resorts in Cancun vs regular hotels",
    "Luxury hotels in Dubai with airport shuttle service",
    "Hotels near Disneyland with family rooms for 5 people",
    "Beachfront hotels in Miami under $200 per night",
    "Hotels in Amsterdam near Van Gogh Museum",
    "Business hotels in Singapore with conference facilities",
    "Romantic hotels in Venice with canal views",
    "Budget hostels in Berlin with private rooms",
    "Hotels in Sydney near Opera House for New Year's Eve",
    "Ski resort hotels in Aspen with spa services",
    "Hotels in Rome walking distance from Colosseum"
]

hotel_booking_query = [
    "Please book hotel near Tajmahal Agra for me only on 24th june",
    "Please book a hotel near India Gate New Delhi on 24th june for only me",
    "Can you book a 4 star hotel under 100 dollar in Barcelona on 23rd july",
    "Can you book a 5 star hotel in Paris near Eiffel Tower",
    ["Can you book a hotel for me in Lucknow which has pool and gym on 1 august", "Can you please cancel my last booking"],
    "Can you please book a hotel for 4 adults on 2nd july with pool in Lucknow",
    "Book me a budget hotel in Goa near Baga Beach for 3 nights starting 15th August",
    "Please reserve a business hotel in Mumbai near airport for tomorrow night",
    "Book a family suite in Jaipur near City Palace for 5 people on 30th September",
    "Can you book a pet-friendly hotel in Bangalore for me and my dog on 10th October",
    "Reserve a luxury resort in Kerala with ayurvedic spa for honeymoon on 25th December",
    "Book a hotel near Gateway of India Mumbai for 2 adults on 18th November",
    "Please book an eco-friendly hotel in Rishikesh with yoga classes for next weekend",
    "Can you reserve a heritage hotel in Udaipur with lake view for 3 nights from 5th July",
    "Book a hotel in Shimla with mountain view and fireplace for winter vacation",
    ["Book a budget hotel near Chennai Central Station for tonight", "Actually, cancel that booking"],
    "Reserve a hotel in Varanasi near ghats for spiritual retreat on 15th January",
    "Book a business hotel in Hyderabad near HITEC City for 5 days from Monday",
    "Please book a resort in Andaman with scuba diving facility for 7 days from 20th March",
    "Can you book a homestay in Darjeeling with breakfast included for 2 people next month"
]

flight_search_query = [
    "Flights from Delhi to Mumbai on June 6",
    "Flights from Bangalore to Kolkata on June 6",
    "Round trip flights from Lucknow to Chennai, departing June 6",
    "Flights from Mumbai to Hyderabad on June 6",
    "Business class flights from Delhi to Bangalore on June 6",
    "Non-stop flights from Chennai to Delhi on June 6",
    "Early morning flights from Kolkata to Mumbai departing before 6 AM on June 6",
    "Flights from Jaipur to Goa on June 6",
    "Economy flights from Hyderabad to Lucknow on June 6",
    "Flights from Ahmedabad to Pune on June 6",
    "Late night flights from Bangalore to Delhi after 9 PM on June 6",
    "Flights from Coimbatore to Mumbai via Bangalore on June 6",
    "Direct flights from Goa to Delhi on June 6",
    "Flights from Surat to Kolkata with one stop on June 6",
    "Flights from Indore to Chennai on June 6",
    "Multi-city flights: Delhi to Mumbai to Bangalore on June 6",
    "Flights from Kochi to Hyderabad on June 6",
    "Connecting flights from Tuticorin to Delhi via Chennai on June 6",
    "Flights from Pune to Jaipur on June 6",
    "Show me all flights from Bhubaneswar to Mumbai on June 6"
]

flight_booking_query = [
    "Please book a flight from Delhi to Bangalore on 6th June for me at 10pm",
    "Book ticket from Lucknow to Mumbai on June 6 early morning",
    "Please book flight from Chennai to Delhi on 6th June for 2 passengers",
    "Book a flight from Mumbai to Kolkata on June 6 afternoon",
    ["Book a flight from Delhi to Hyderabad on June 6", "Cancel my last booking"],
    "Reserve seats on Bangalore to Goa flight on 6th June for family of 4",
    "Book business class from Delhi to Chennai on June 6 morning flight",
    "Please book connecting flight from Ahmedabad to Kolkata via Mumbai on June 6",
    "Book 3 tickets from Jaipur to Bangalore on 6th June evening flight",
    "Reserve flight from Coimbatore to Delhi on June 6 for tomorrow",
    "Book round trip from Lucknow to Hyderabad on June 6",
    "Please book flight from Kochi to Mumbai on 6th June for 2 adults 1 child",
    ["Book morning flight from Surat to Delhi on June 6", "Change it to evening flight"],
    "Reserve flight from Pune to Chennai on June 6 with extra baggage",
    "Book flight from Goa to Bangalore on 6th June window seat preferred",
    "Please book Delhi to Mumbai to Bangalore multi-city on June 6",
    "Book economy ticket from Kolkata to Jaipur on June 6",
    "Reserve flight from Indore to Hyderabad on 6th June for senior citizen",
    "Book direct flight from Bhubaneswar to Delhi on June 6",
    "Please book last available seat from Tuticorin to Mumbai via Chennai on June 6"
]

general_query = [
    "What's the weather like in Mumbai?",
    "Tell me about tourist attractions in Jaipur",
    "What documents do I need for domestic travel in India?",
    "Best time to visit Kerala?",
    "How to reach Taj Mahal from Delhi?",
    "What are the baggage rules for domestic flights?",
    "Currency exchange rates for USD to INR",
    "Travel insurance options for international trips",
    "Visa requirements for Indians traveling to Thailand",
    "Best restaurants in Bangalore",
    "Local transportation options in Goa",
    "Cultural etiquette tips for visiting temples in India",
    "Packing essentials for Ladakh trip",
    "Train routes from Mumbai to Pune",
    "Adventure activities available in Rishikesh",
    "Shopping markets in Delhi",
    "Beach resorts comparison in Andaman",
    "Mountain trekking guides for Himachal",
    "Festival calendar for Rajasthan 2025",
    "Travel safety tips for solo female travelers in India"
]